<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>Document</title>
</head>
<body>
<form action="./createpdf" enctype="multipart/form-data" method="post">
    <lable for="upload-btn">文件</lable>
    <lable id="upload-btn"><input type="file" name="excel_one" /></lable>
    <br><input type="submit">
</form>
</body>
</html>